### ISSUE TITLE
'instant' crash with OBS studio 26.1.1

### ISSUE THREAD

**Issue by TomberWolf** [fredemmott/streaming-remote#12]
OBS Studio: 26.1.1

Crashes instandly

**Comment by fredemmott** [comment]
Sorry, I need more information:
- what client are you using? webui or streamdeck?
- what operating system? windows or macos? 32- or 64- bit?
- what crashes? OBS or the client?
- when does it crash? when opening OBS, taking some other action in OBS, when opening/connecting in the client, or when taking some other action in the client?
- are you using any other OBS plugins? what are they, and are they definitely up to date? Many plugins need to be updated for v26.1 due to the change in Qt version

If you're able to share the OBS crash log, that would be very useful.

With x64 OBS 26.1.1 on Windows 10 H2 2020, I'm able to start/stop recording and streaming via web UI and streamdeck clients, so it's likely either an ordering issue or a problem/interaction with another plugin

**Comment by fredemmott** [comment]
If you have the time, it would also be useful if you could test with the versions at the bottom of https://github.com/fredemmott/streaming-remote/actions/runs/546552481

**Comment by fredemmott** [comment]
Perhaps this is a variant of #13 ?

**Comment by fredemmott** [comment]
https://github.com/fredemmott/streaming-remote/actions/runs/548731811 fixes #13

**Comment by fredemmott** [comment]
Sorry for the spam, https://github.com/fredemmott/streaming-remote/releases/tag/v3.0.0alpha1 fixes a few more, but still need more information to figure out if it likely fixed the situation you encountered.

**Comment by fredemmott** [comment]
Closing as there's not enough information to act on this. If you're still encountering crashes with the release above, please comment with the information I asked for above. If you're not able to reopen, I will reopen this when you comment if needed. Thanks!
